name = input("Enter your name : ")
age = input("Enter your age : ")
print("Hello " + name + "! You are "+ age)

print("\n-------Basic calculator-----------")
num1 = input("Enter number: ")
num2 = input("Enter another number: ")
result = float(num1) + float(num2)
print(result)
print("-----------------------------------")
